#!/bin/sh /etc/rc.common

START=95
USE_PROCD=1

start_service() {
    logger -t monitor_service "start_service entered"
    procd_open_instance
    procd_set_param command /usr/bin/app-monitor
    procd_set_param respawn
    procd_close_instance
}
